### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [YoannQDQ/qgis-multilayer-select#1]
# Problem
What does this plugin offer which is not available in core

**Comment by YoannQDQ** [comment]
Unless I'm mistaken, the selection tools available in core only select features on the active layer. The whole point of this plugin is to allow feature selection on every vector layer without having to set them as active in the layer tree. So one can draw a rectangle on the canvas, and every feature contained in the rectangle is selected, regardless of the layer they belong to. Additionnaly, if one selects only one feature, the layer the selected feature belongs to is automatically set as active.

**Comment by NyakudyaA** [comment]
I tried to  test and got an error
![install-error](https://user-images.githubusercontent.com/2510900/91633343-c892c300-e9e7-11ea-9790-19a0feffc149.png)

**Comment by YoannQDQ** [comment]
Correct me if I'm wrong, but it seems you downloaded the repo from Github, and then copied it to the QGIS plugin repo to test the plugin. 

That's not how it is suposed to be installed; the repo does not contain py files compiled from .ui and .qrc files, those are created with the pb_tool. 

Could you just download the plugin from the [QGIS Python Plugins Repository](https://plugins.qgis.org/plugins/multilayerselect/version/1.0.1/download/ ) and try again ?

**Comment by NyakudyaA** [comment]
> Correct me if I'm wrong, but it seems you downloaded the repo from Github, and then copied it to the QGIS plugin repo to test the plugin. 
> 
> 
> 
> That's not how it is suposed to be installed; the repo does not contain py files compiled from .ui and .qrc files, those are created with the pb_tool. 
> 
> 
> 
> Could you just download the plugin from the [QGIS Python Plugins Repository](https://plugins.qgis.org/plugins/multilayerselect/version/1.0.1/download/ ) and try again ?

Ideally the contents of the repo should be identical to what you submit to the plugin repo. Other plugins work the same way. That's why there is the option to install from zip file. I will test when I am on a computer

**Comment by NyakudyaA** [comment]
@YoannQDQ Can you please update the repo to match the plugin you are uploading

**Comment by YoannQDQ** [comment]
According to the [guidelines ](https://docs.qgis.org/3.10/en/docs/pyqgis_developer_cookbook/plugins/releasing.html#code-and-help) from the official documentation, geenrated files shouldn't be included in the repo. 

Additionaly, popular plugins like [Plugin Builder](https://github.com/g-sherman/Qgis-Plugin-Builder) and [QuickMapService ](https://github.com/nextgis/quickmapservices) also cannot be installed from the zip file downloaded from Github.

Not what is the correct approach here. I was under the impression that the "Install from zip" option in the plugin manager was mean to be used with zip files downloaded from the QGIS Python Plugins Repository.

Anyway, the plugin was approved so I guess I can close the issue.

**Comment by NyakudyaA** [comment]
@YoannQDQ I approved the plugin because it installs properly. The install from zip is used to download the plugin from GitHub then install. The most use case of this is when a user wants to install a bleeding-edge ( in development) then they just heard to the repo. The only files that should not be included in the plugin repo are _pycache,.pyc files
